### ISSUE TITLE
Duplicate greeting message

### ISSUE THREAD

**Issue by serin-delaunay** [backspace/slack-statsbot#17]
On detecting that I'm a new arrival on a Slack, statsbot sends a private message introducing itself, ending with "If you don't want to answer that's okay, I won't ask again." However, in my case it sent the message twice, with the same timestamp. Presumably that's not intended.

**Comment by backspace** [comment]
Hey, thanks for writing in about this. That’s definitely not the desired behaviour!

I assume you’re talking about on the LGBTQ in Tech Slack?

I’m pretty swamped right now but I’ll hopefully be able to look into it some time this week.
