### ISSUE TITLE
Improve identification process.

### ISSUE THREAD

**Issue by allison-lara** [backspace/slack-statsbot#2]
Move away from `true`/`false` to a more narrative and friendly identification process.

**Comment by backspace** [comment]
Definitely. We could disappear down the nightmare spiral of natural language processing, but I think even a small change will improve things.

**Comment by backspace** [comment]
This could perhaps use further refinement. You could trick it by saying “I’m not NOT a man” but really, how far do we have to go to accommodate that sort of thing? haha. It does include an “if I got it wrong” statement and explanation of what would be understood, which seems sufficient for now.
