### ISSUE TITLE
Delve into the mission statement more

### ISSUE THREAD

**Issue by theroux** [backspace/slack-statsbot#7]
> This is a Slack bot that monitors and reports on who is speaking in channels. It is an experiment by users of the LGBTQ in Technology Slack.

This mission statement describes the "what" but not the "why."

Someone said this, which is a good start:

> I think the way to think about the bot is that it's a gentle reminder that even though our numbers are roughly 50% men / 50% not-men, 50% not-men _[typo, should be "men"]_ are speaking more in the larger group spaces. We should look at it both as an encouragement for not-men to speak up ("Your voices are wanted and respected here"), and for men to engage in conversation with not-men (as in - make sure you don't run rough-shod over conversation points brought up by not-men, which is shockingly easy to do).

Links / resources for the uninitiated to learn even more than can be communicated in a short mission statement would also be helpful.

**Comment by rhwlo** [comment]
@theroux I assume that it should read:

> […] even though our numbers are roughly 50% men / 50% not-men, **50% men** are speaking more […]

?

**Comment by theroux** [comment]
typo i'm sure, thanks! updated.

**Comment by backspace** [comment]
Let me know if you think there should be more there, of course it can continue to evolve.

**Comment by theroux** [comment]
great! thanks!
