### ISSUE TITLE
Restore Deploy to Heroku functionality

### ISSUE THREAD

**Issue by backspace** [backspace/slack-statsbot#8]
Since I added migrations, there’s no reliable way to deploy to Heroku. I added a `postdeploy` script to run the migrations:

```
sequelize --env production db:migrate
```

It produces the error mentioned [here](https://github.com/gulpjs/gulp/issues/873), though downgrading to io.js 1.0.2 produces a similar one:

```
Error: Cannot find module '/app/node_modules/sequelize-cli/node_modules/gulp/node_modules/v8flags/cache/3.31.74.1.flags.json'
```

Since it’s unlikely that people are rushing out to deploy this to Heroku, I feel okay leaving it broken for a while.

**Comment by tr1age** [comment]
This seems to be fixed. Am I wrong? I look in the config for the app and it is set to 1 on the web.

**Comment by backspace** [comment]
hmm, could be, I haven’t tried it in months. I’ll come back to this next week and close it if it’s fixed, thanks for the notice.

**Comment by tr1age** [comment]
[image: Inline image 1]

Is this correct? Cause this is how it set it up from deploy.

Although I still can't seem to get the bot to run in Slack.

**Comment by backspace** [comment]
What if you change the dynos to be one `worker` one instead of a `web` one?

**Comment by backspace** [comment]
https://stackoverflow.com/questions/30846776/use-n-web-dynos-and-m-worker-dynos-on-heroku-review-app/32697027#32697027
